<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>unicornproperties</groupId>
    <artifactId>UnicornProperties</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>unicorn_contracts/ContractsService</module>
        <module>unicorn_approvals/ApprovalsService</module>
        <module>unicorn_web/ApprovalService</module>
        <module>unicorn_web/SearchService</module>
        <module>unicorn_web/Common</module>
    </modules>
</project>