version: 0.1
default:
  global:
    parameters:
      stack_name: "uni-prop-local-properties"
      s3_prefix: "uni-prop-local-properties"
      resolve_s3: true
      resolve_image_repositories: true
  build:
    parameters:
      cached: true
      parallel: true
  deploy:
    parameters:
      confirm_changeset: false
      capabilities: "CAPABILITY_IAM"
      disable_rollback: true
      parameter_overrides:
        - "Stage=local"
      image_repositories: []
  validate:
    parameters:
      lint: true
  sync:
    parameters:
      watch: true
  local_start_api:
    parameters:
      warm_containers: "EAGER"
  local_start_lambda:
    parameters:
      warm_containers: "EAGER"

subscriber-policies:
  global:
    parameters:
      stack_name: uni-prop-local-properties-subscriber-policies
      s3_prefix: uni-prop-local-properties-subscriber-policies
      resolve_s3: true
  deploy:
    parameters:
      template_file: ./integration/subscriber-policies.yaml
      confirm_changeset: false
      fail_on_empty_changeset: false
      on_failure: ROLLBACK
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - "Stage=local"

subscriptions:
  global:
    parameters:
      stack_name: uni-prop-local-properties-subscriptions
      s3_prefix: uni-prop-local-properties-subscriptions
      resolve_s3: true
  deploy:
    parameters:
      template_file: ./integration/subscriptions.yaml
      confirm_changeset: false
      fail_on_empty_changeset: false
      on_failure: ROLLBACK
      capabilities: CAPABILITY_IAM
      parameter_overrides:
        - "Stage=local"